Search.appendIndex(
    [
                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract",
            "name": "ResponseHandlerAbstract",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020JSON\u0020response\u0020after\u0020an\u0020initialization\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html#method_handle"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020if\u0020all\u0020required\u0020fields\u0020are\u0020present\u0020in\u0020the\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html#method_check"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decode\u0020the\u0020JSON\u0020response\u0020string\u0020into\u0020an\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html#method_decode"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020the\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts\\ResponseHandlerAbstract\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020instance.",
            "url": "classes/EasyPay-PHP-Yigim-Abstracts-ResponseHandlerAbstract.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\BatchCloseCommandAttributer",
            "name": "BatchCloseCommandAttributer",
            "summary": "Class\u0020BatchCloseCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-BatchCloseCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\CancellationCommandAttributer",
            "name": "CancellationCommandAttributer",
            "summary": "Class\u0020CancellationCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-CancellationCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\DirectPaymentCommandAttributer",
            "name": "DirectPaymentCommandAttributer",
            "summary": "Class\u0020DirectPaymentCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-DirectPaymentCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\InitializationCommandAttributer",
            "name": "InitializationCommandAttributer",
            "summary": "Class\u0020InitializationCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-InitializationCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\PaymentClearanceCommandAttributer",
            "name": "PaymentClearanceCommandAttributer",
            "summary": "Class\u0020PaymentClearanceCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-PaymentClearanceCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\RefundCommandAttributer",
            "name": "RefundCommandAttributer",
            "summary": "Class\u0020RefundCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-RefundCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers\\StatusCommandAttributer",
            "name": "StatusCommandAttributer",
            "summary": "Class\u0020StatusCommandAttributer",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Attributers-StatusCommandAttributer.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\BatchCloseCommandEndpointProvider",
            "name": "BatchCloseCommandEndpointProvider",
            "summary": "Class\u0020BatchCloseCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-BatchCloseCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\BatchCloseCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020batch\u0020closure\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-BatchCloseCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\CancellationCommandEndpointProvider",
            "name": "CancellationCommandEndpointProvider",
            "summary": "Class\u0020CancellationCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-CancellationCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\CancellationCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-CancellationCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\DirectPaymentCommandEndpointProvider",
            "name": "DirectPaymentCommandEndpointProvider",
            "summary": "Class\u0020DirectPaymentCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-DirectPaymentCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\DirectPaymentCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-DirectPaymentCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\InitializationCommandEndpointProvider",
            "name": "InitializationCommandEndpointProvider",
            "summary": "Class\u0020InitializationCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-InitializationCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\InitializationCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020initialization\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-InitializationCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\PaymentClearanceCommandEndpointProvider",
            "name": "PaymentClearanceCommandEndpointProvider",
            "summary": "Class\u0020PaymentClearanceCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-PaymentClearanceCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\PaymentClearanceCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020\u0022payment\u0020clearance\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-PaymentClearanceCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\RefundCommandEndpointProvider",
            "name": "RefundCommandEndpointProvider",
            "summary": "Class\u0020RefundCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-RefundCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\RefundCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-RefundCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\StatusCommandEndpointProvider",
            "name": "StatusCommandEndpointProvider",
            "summary": "Class\u0020StatusCommandEndpointProvider",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-StatusCommandEndpointProvider.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders\\StatusCommandEndpointProvider\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-EndpointProviders-StatusCommandEndpointProvider.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\BatchCloseCommandFactory",
            "name": "BatchCloseCommandFactory",
            "summary": "Class\u0020BatchCloseCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-BatchCloseCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\BatchCloseCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020attributer.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-BatchCloseCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\BatchCloseCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020response\u0020handler.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-BatchCloseCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\BatchCloseCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020endpoint\u0020provider.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-BatchCloseCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\CancellationCommandFactory",
            "name": "CancellationCommandFactory",
            "summary": "Class\u0020CancellationCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-CancellationCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\CancellationCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020attributer.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-CancellationCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\CancellationCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020response\u0020handler.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-CancellationCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\CancellationCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020endpoint\u0020provider.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-CancellationCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\DirectPaymentCommandFactory",
            "name": "DirectPaymentCommandFactory",
            "summary": "Class\u0020DirectPaymentCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-DirectPaymentCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\DirectPaymentCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020a\u0020response\u0020handler\u0020instance\u0020for\u0020the\u0020\u0022direct\u0020payment\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-DirectPaymentCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\DirectPaymentCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020endpoint\u0020provider\u0020instance\u0020for\u0020the\u0020\u0022direct\u0020payment\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-DirectPaymentCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\DirectPaymentCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020attributer\u0020instance\u0020for\u0020the\u0020\u0022direct\u0020payment\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-DirectPaymentCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\InitializationCommandFactory",
            "name": "InitializationCommandFactory",
            "summary": "Class\u0020InitializationCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-InitializationCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\InitializationCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020attributer.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-InitializationCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\InitializationCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020response\u0020handler.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-InitializationCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\InitializationCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020endpoint\u0020provider.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-InitializationCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\PaymentClearanceCommandFactory",
            "name": "PaymentClearanceCommandFactory",
            "summary": "Class\u0020PaymentClearanceCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-PaymentClearanceCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\PaymentClearanceCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020attributer\u0020instance\u0020for\u0020the\u0020\u0022payment\u0020clearance\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-PaymentClearanceCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\PaymentClearanceCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020endpoint\u0020provider\u0020instance\u0020for\u0020the\u0020\u0022payment\u0020clearance\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-PaymentClearanceCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\PaymentClearanceCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020a\u0020response\u0020handler\u0020instance\u0020for\u0020the\u0020\u0022payment\u0020clearance\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-PaymentClearanceCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\RefundCommandFactory",
            "name": "RefundCommandFactory",
            "summary": "Class\u0020RefundCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-RefundCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\RefundCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020attributer.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-RefundCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\RefundCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020response\u0020handler.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-RefundCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\RefundCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020endpoint\u0020provider.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-RefundCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\StatusCommandFactory",
            "name": "StatusCommandFactory",
            "summary": "Class\u0020StatusCommandFactory",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-StatusCommandFactory.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\StatusCommandFactory\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020attributer\u0020instance\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-StatusCommandFactory.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\StatusCommandFactory\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020endpoint\u0020provider\u0020instance\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-StatusCommandFactory.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories\\StatusCommandFactory\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020a\u0020response\u0020handler\u0020instance\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-Factories-StatusCommandFactory.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\BatchCloseCommandResponseData",
            "name": "BatchCloseCommandResponseData",
            "summary": "Class\u0020BatchCloseCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-BatchCloseCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\CancellationCommandResponseData",
            "name": "CancellationCommandResponseData",
            "summary": "Class\u0020CancellationCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-CancellationCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\DirectPaymentCommandResponseData",
            "name": "DirectPaymentCommandResponseData",
            "summary": "Class\u0020DirectPaymentCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-DirectPaymentCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\InitializationCommandResponseData",
            "name": "InitializationCommandResponseData",
            "summary": "Class\u0020InitializationCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-InitializationCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\PaymentClearanceCommandResponseData",
            "name": "PaymentClearanceCommandResponseData",
            "summary": "Class\u0020PaymentClearanceCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-PaymentClearanceCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\RefundCommandResponseData",
            "name": "RefundCommandResponseData",
            "summary": "Class\u0020RefundCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-RefundCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData\\StatusCommandResponseData",
            "name": "StatusCommandResponseData",
            "summary": "Class\u0020StatusCommandResponseData",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseData-StatusCommandResponseData.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\BatchCloseCommandResponseHandler",
            "name": "BatchCloseCommandResponseHandler",
            "summary": "Class\u0020BatchCloseCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-BatchCloseCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\BatchCloseCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-BatchCloseCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\BatchCloseCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022closing\u0020of\u0020batch\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-BatchCloseCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\CancellationCommandResponseHandler",
            "name": "CancellationCommandResponseHandler",
            "summary": "Class\u0020CancellationCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-CancellationCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\CancellationCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-CancellationCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\CancellationCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-CancellationCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\DirectPaymentCommandResponseHandler",
            "name": "DirectPaymentCommandResponseHandler",
            "summary": "Class\u0020DirectPaymentCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-DirectPaymentCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\DirectPaymentCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-DirectPaymentCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\DirectPaymentCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022direct\u0020payment\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-DirectPaymentCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\InitializationCommandResponseHandler",
            "name": "InitializationCommandResponseHandler",
            "summary": "Class\u0020InitializationCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-InitializationCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\InitializationCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-InitializationCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\InitializationCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-InitializationCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\PaymentClearanceCommandResponseHandler",
            "name": "PaymentClearanceCommandResponseHandler",
            "summary": "Class\u0020PaymentClearanceCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-PaymentClearanceCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\PaymentClearanceCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-PaymentClearanceCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\PaymentClearanceCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-PaymentClearanceCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\RefundCommandResponseHandler",
            "name": "RefundCommandResponseHandler",
            "summary": "Class\u0020RefundCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-RefundCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\RefundCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-RefundCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\RefundCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022payment\u0020refund\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-RefundCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\StatusCommandResponseHandler",
            "name": "StatusCommandResponseHandler",
            "summary": "Class\u0020StatusCommandResponseHandler",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-StatusCommandResponseHandler.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\StatusCommandResponseHandler\u003A\u003AgetResponseFields\u0028\u0029",
            "name": "getResponseFields",
            "summary": "Get\u0020required\u0020response\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-StatusCommandResponseHandler.html#method_getResponseFields"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers\\StatusCommandResponseHandler\u003A\u003AgetResponseDataClass\u0028\u0029",
            "name": "getResponseDataClass",
            "summary": "Get\u0020the\u0020response\u0020data\u0020class\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Commands-ResponseHandlers-StatusCommandResponseHandler.html#method_getResponseDataClass"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandAttributerContract",
            "name": "CommandAttributerContract",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandAttributerContract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandAttributerContract\u003A\u003AgetAttributes\u0028\u0029",
            "name": "getAttributes",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandAttributerContract.html#method_getAttributes"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandEndpointProviderContract",
            "name": "CommandEndpointProviderContract",
            "summary": "Interface\u0020CommandEndpointProviderContract",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandEndpointProviderContract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandEndpointProviderContract\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "Get\u0020the\u0020endpoint\u0020URL\u0020for\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandEndpointProviderContract.html#method_getEndpoint"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandExecutorContract",
            "name": "CommandExecutorContract",
            "summary": "Interface\u0020CommandExecutorContract",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandExecutorContract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandExecutorContract\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Executes\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandExecutorContract.html#method_execute"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandExecutorContract\u003A\u003AfieldBuilder\u0028\u0029",
            "name": "fieldBuilder",
            "summary": "Retrieves\u0020the\u0020command\u0020attributer\u0020for\u0020building\u0020command\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandExecutorContract.html#method_fieldBuilder"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandFactoryContract",
            "name": "CommandFactoryContract",
            "summary": "CommandFactoryContract\u0020interface.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandFactoryContract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandFactoryContract\u003A\u003AcreateAttributer\u0028\u0029",
            "name": "createAttributer",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020attributer.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandFactoryContract.html#method_createAttributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandFactoryContract\u003A\u003AcreateResponseHandler\u0028\u0029",
            "name": "createResponseHandler",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020response\u0020handler.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandFactoryContract.html#method_createResponseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\CommandFactoryContract\u003A\u003AcreateProvider\u0028\u0029",
            "name": "createProvider",
            "summary": "Create\u0020an\u0020instance\u0020of\u0020the\u0020command\u0020provider.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-CommandFactoryContract.html#method_createProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\ResponseDataContract",
            "name": "ResponseDataContract",
            "summary": "ResponseDataContract\u0020interface.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-ResponseDataContract.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts\\ResponseDataContract\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020response\u0020data\u0020and\u0020return\u0020self.",
            "url": "classes/EasyPay-PHP-Yigim-Contracts-ResponseDataContract.html#method_handle"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint",
            "name": "Endpoint",
            "summary": "Enum\u0020class\u0020representing\u0020the\u0020endpoints\u0020for\u0020various\u0020operations\u0020in\u0020the\u0020Yigim\u0020payment\u0020system.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003AINITIALIZATION",
            "name": "INITIALIZATION",
            "summary": "The\u0020endpoint\u0020for\u0020initializing\u0020a\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_INITIALIZATION"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003ASTATUS",
            "name": "STATUS",
            "summary": "The\u0020endpoint\u0020for\u0020checking\u0020the\u0020status\u0020of\u0020a\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_STATUS"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003ADIRECT_PAYMENT",
            "name": "DIRECT_PAYMENT",
            "summary": "The\u0020endpoint\u0020for\u0020executing\u0020a\u0020direct\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_DIRECT_PAYMENT"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003ACLEARANCE",
            "name": "CLEARANCE",
            "summary": "The\u0020endpoint\u0020for\u0020clearing\u0020a\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_CLEARANCE"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003ACANCELLATION",
            "name": "CANCELLATION",
            "summary": "The\u0020endpoint\u0020for\u0020canceling\u0020a\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_CANCELLATION"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003AREFUND",
            "name": "REFUND",
            "summary": "The\u0020endpoint\u0020for\u0020refunding\u0020a\u0020payment.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_REFUND"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums\\Endpoint\u003A\u003ABATCH_CLOSE",
            "name": "BATCH_CLOSE",
            "summary": "The\u0020endpoint\u0020for\u0020batch\u0020closure.",
            "url": "classes/EasyPay-PHP-Yigim-Enums-Endpoint.html#enumcase_BATCH_CLOSE"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\CommandExecutionFailedException",
            "name": "CommandExecutionFailedException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-CommandExecutionFailedException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidAmountException",
            "name": "InvalidAmountException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidAmountException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidCallbackURLException",
            "name": "InvalidCallbackURLException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidCallbackURLException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidCurrencyException",
            "name": "InvalidCurrencyException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidCurrencyException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidExpiryArgument",
            "name": "InvalidExpiryArgument",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidExpiryArgument.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidLanguageException",
            "name": "InvalidLanguageException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidLanguageException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\InvalidTokenException",
            "name": "InvalidTokenException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-InvalidTokenException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\ResponseHandlerJsonDecodeException",
            "name": "ResponseHandlerJsonDecodeException",
            "summary": "Class\u0020ResponseHandlerJsonDecodeException",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-ResponseHandlerJsonDecodeException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\ResponseHasMissingFieldsException",
            "name": "ResponseHasMissingFieldsException",
            "summary": "Class\u0020ResponseHasMissingFieldsException",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-ResponseHasMissingFieldsException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\TypeUnsupportedArgumentException",
            "name": "TypeUnsupportedArgumentException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-TypeUnsupportedArgumentException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions\\XTypeUnsupportedArgumentException",
            "name": "XTypeUnsupportedArgumentException",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Exceptions-XTypeUnsupportedArgumentException.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor",
            "name": "CommandExecutor",
            "summary": "Class\u0020CommandExecutor",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CommandExecutor\u0020constructor.",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#method___construct"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Executes\u0020the\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#method_execute"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003AfieldBuilder\u0028\u0029",
            "name": "fieldBuilder",
            "summary": "Retrieves\u0020the\u0020command\u0020attributer\u0020for\u0020building\u0020command\u0020fields.",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#method_fieldBuilder"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003AgetURL\u0028\u0029",
            "name": "getURL",
            "summary": "Builds\u0020the\u0020URL\u0020for\u0020the\u0020command\u0020execution.",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#method_getURL"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003A\u0024attributer",
            "name": "attributer",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#property_attributer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003A\u0024responseHandler",
            "name": "responseHandler",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#property_responseHandler"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors\\CommandExecutor\u003A\u003A\u0024endpointProvider",
            "name": "endpointProvider",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Executors-CommandExecutor.html#property_endpointProvider"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade",
            "name": "CommandFacade",
            "summary": "Class\u0020CommandFacade",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003Ainitialization\u0028\u0029",
            "name": "initialization",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022initialization\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_initialization"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022status\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_status"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003AdirectPayment\u0028\u0029",
            "name": "directPayment",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022direct\u0020payment\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_directPayment"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003ApaymentClearance\u0028\u0029",
            "name": "paymentClearance",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022payment\u0020clearance\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_paymentClearance"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003Acancellation\u0028\u0029",
            "name": "cancellation",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022cancellation\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_cancellation"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003Arefund\u0028\u0029",
            "name": "refund",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022payment\u0020refund\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_refund"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades\\CommandFacade\u003A\u003AbatchClose\u0028\u0029",
            "name": "batchClose",
            "summary": "Prepares\u0020the\u0020command\u0020executor\u0020for\u0020the\u0020\u0022closing\u0020of\u0020batch\u0022\u0020command.",
            "url": "classes/EasyPay-PHP-Yigim-Facades-CommandFacade.html#method_batchClose"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers\\Arr",
            "name": "Arr",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Helpers-Arr.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers\\Arr\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Get\u0020a\u0020value\u0020from\u0020an\u0020array\u0020using\u0020\u0022dot\u0022\u0020notation",
            "url": "classes/EasyPay-PHP-Yigim-Helpers-Arr.html#method_get"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers\\Arr\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "Check\u0020if\u0020a\u0020key\u0020exists\u0020in\u0020an\u0020array",
            "url": "classes/EasyPay-PHP-Yigim-Helpers-Arr.html#method_exists"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers\\Arr\u003A\u003Aforget\u0028\u0029",
            "name": "forget",
            "summary": "Remove\u0020a\u0020value\u0020from\u0020an\u0020array\u0020using\u0020\u0022dot\u0022\u0020notation.",
            "url": "classes/EasyPay-PHP-Yigim-Helpers-Arr.html#method_forget"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers\\Arr\u003A\u003Apull\u0028\u0029",
            "name": "pull",
            "summary": "Retrieve\u0020a\u0020value\u0020from\u0020an\u0020array\u0020using\u0020\u0022dot\u0022\u0020notation\u0020and\u0020remove\u0020it.",
            "url": "classes/EasyPay-PHP-Yigim-Helpers-Arr.html#method_pull"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\AmountCommandAttributeTrait",
            "name": "AmountCommandAttributeTrait",
            "summary": "Trait\u0020AmountCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-AmountCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\AmountCommandAttributeTrait\u003A\u003AsetAmount\u0028\u0029",
            "name": "setAmount",
            "summary": "Set\u0020the\u0020amount\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-AmountCommandAttributeTrait.html#method_setAmount"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\AmountCommandAttributeTrait\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "Get\u0020the\u0020amount\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-AmountCommandAttributeTrait.html#method_getAmount"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\AmountCommandAttributeTrait\u003A\u003A\u0024amount",
            "name": "amount",
            "summary": "The\u0020payment\u0020amount\u0020in\u0020coins.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-AmountCommandAttributeTrait.html#property_amount"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\BillerCommandAttributeTrait",
            "name": "BillerCommandAttributeTrait",
            "summary": "Trait\u0020BillerCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-BillerCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\BillerCommandAttributeTrait\u003A\u003AsetBiller\u0028\u0029",
            "name": "setBiller",
            "summary": "Set\u0020the\u0020biller\u0020name.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-BillerCommandAttributeTrait.html#method_setBiller"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\BillerCommandAttributeTrait\u003A\u003AgetBiller\u0028\u0029",
            "name": "getBiller",
            "summary": "Get\u0020the\u0020biller\u0020name.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-BillerCommandAttributeTrait.html#method_getBiller"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\BillerCommandAttributeTrait\u003A\u003A\u0024biller",
            "name": "biller",
            "summary": "The\u0020name\u0020of\u0020the\u0020biller\u0020provided\u0020by\u0020the\u0020acquirer.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-BillerCommandAttributeTrait.html#property_biller"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CallbackCommandAttributeTrait",
            "name": "CallbackCommandAttributeTrait",
            "summary": "Trait\u0020CallbackCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CallbackCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CallbackCommandAttributeTrait\u003A\u003AsetCallback\u0028\u0029",
            "name": "setCallback",
            "summary": "Set\u0020the\u0020callback\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CallbackCommandAttributeTrait.html#method_setCallback"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CallbackCommandAttributeTrait\u003A\u003AgetCallback\u0028\u0029",
            "name": "getCallback",
            "summary": "Get\u0020the\u0020callback\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CallbackCommandAttributeTrait.html#method_getCallback"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CallbackCommandAttributeTrait\u003A\u003A\u0024callback",
            "name": "callback",
            "summary": "The\u0020webhook\u0020URL\u0020triggered\u0020when\u0020the\u0020payment\u0020status\u0020changes.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CallbackCommandAttributeTrait.html#property_callback"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CscCommandAttributeTrait",
            "name": "CscCommandAttributeTrait",
            "summary": "Trait\u0020CscCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CscCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CscCommandAttributeTrait\u003A\u003AsetCsc\u0028\u0029",
            "name": "setCsc",
            "summary": "Set\u0020the\u0020Card\u0020Security\u0020Code.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CscCommandAttributeTrait.html#method_setCsc"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CscCommandAttributeTrait\u003A\u003AgetCsc\u0028\u0029",
            "name": "getCsc",
            "summary": "Get\u0020the\u0020Card\u0020Security\u0020Code.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CscCommandAttributeTrait.html#method_getCsc"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CscCommandAttributeTrait\u003A\u003A\u0024csc",
            "name": "csc",
            "summary": "The\u0020Card\u0020Security\u0020Code.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CscCommandAttributeTrait.html#property_csc"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CurrencyCommandAttributeTrait",
            "name": "CurrencyCommandAttributeTrait",
            "summary": "Trait\u0020CurrencyCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CurrencyCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CurrencyCommandAttributeTrait\u003A\u003AsetCurrency\u0028\u0029",
            "name": "setCurrency",
            "summary": "Set\u0020the\u0020currency\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CurrencyCommandAttributeTrait.html#method_setCurrency"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CurrencyCommandAttributeTrait\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "Get\u0020the\u0020currency\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CurrencyCommandAttributeTrait.html#method_getCurrency"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\CurrencyCommandAttributeTrait\u003A\u003A\u0024currency",
            "name": "currency",
            "summary": "The\u0020numeric\u0020ISO\u00204217\u0020currency\u0020code.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-CurrencyCommandAttributeTrait.html#property_currency"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\DescriptionCommandAttributeTrait",
            "name": "DescriptionCommandAttributeTrait",
            "summary": "Trait\u0020DescriptionCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-DescriptionCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\DescriptionCommandAttributeTrait\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Set\u0020the\u0020payment\u0020description.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-DescriptionCommandAttributeTrait.html#method_setDescription"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\DescriptionCommandAttributeTrait\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Get\u0020the\u0020payment\u0020description.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-DescriptionCommandAttributeTrait.html#method_getDescription"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\DescriptionCommandAttributeTrait\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020payment\u0020description\u0020for\u0020displaying\u0020on\u0020the\u0020card\u0020input\u0020page.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-DescriptionCommandAttributeTrait.html#property_description"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExpiryCommandAttributeTrait",
            "name": "ExpiryCommandAttributeTrait",
            "summary": "Trait\u0020ExpiryCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExpiryCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExpiryCommandAttributeTrait\u003A\u003AsetExpiry\u0028\u0029",
            "name": "setExpiry",
            "summary": "Set\u0020the\u0020expiry\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExpiryCommandAttributeTrait.html#method_setExpiry"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExpiryCommandAttributeTrait\u003A\u003AgetExpiry\u0028\u0029",
            "name": "getExpiry",
            "summary": "Get\u0020the\u0020expiry\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExpiryCommandAttributeTrait.html#method_getExpiry"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExpiryCommandAttributeTrait\u003A\u003A\u0024expiry",
            "name": "expiry",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExpiryCommandAttributeTrait.html#property_expiry"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExtraCommandAttributeTrait",
            "name": "ExtraCommandAttributeTrait",
            "summary": "Trait\u0020ExtraCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExtraCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExtraCommandAttributeTrait\u003A\u003AsetExtra\u0028\u0029",
            "name": "setExtra",
            "summary": "Set\u0020the\u0020extra\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExtraCommandAttributeTrait.html#method_setExtra"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExtraCommandAttributeTrait\u003A\u003AgetExtra\u0028\u0029",
            "name": "getExtra",
            "summary": "Get\u0020the\u0020extra\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExtraCommandAttributeTrait.html#method_getExtra"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ExtraCommandAttributeTrait\u003A\u003A\u0024extra",
            "name": "extra",
            "summary": "The\u0020URL\u002Dencoded\u0020parameters.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ExtraCommandAttributeTrait.html#property_extra"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\PanCommandAttributeTrait",
            "name": "PanCommandAttributeTrait",
            "summary": "Trait\u0020PanCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-PanCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\PanCommandAttributeTrait\u003A\u003AsetPan\u0028\u0029",
            "name": "setPan",
            "summary": "Set\u0020the\u0020PAN\u0020\u0028Primary\u0020Account\u0020Number\u0029\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-PanCommandAttributeTrait.html#method_setPan"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\PanCommandAttributeTrait\u003A\u003AgetPan\u0028\u0029",
            "name": "getPan",
            "summary": "Get\u0020the\u0020PAN\u0020\u0028Primary\u0020Account\u0020Number\u0029\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-PanCommandAttributeTrait.html#method_getPan"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\PanCommandAttributeTrait\u003A\u003A\u0024pan",
            "name": "pan",
            "summary": "",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-PanCommandAttributeTrait.html#property_pan"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ReferenceCommandAttributeTrait",
            "name": "ReferenceCommandAttributeTrait",
            "summary": "Trait\u0020ReferenceCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ReferenceCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ReferenceCommandAttributeTrait\u003A\u003AsetReference\u0028\u0029",
            "name": "setReference",
            "summary": "Set\u0020the\u0020reference\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ReferenceCommandAttributeTrait.html#method_setReference"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ReferenceCommandAttributeTrait\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "Get\u0020the\u0020reference\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ReferenceCommandAttributeTrait.html#method_getReference"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\ReferenceCommandAttributeTrait\u003A\u003A\u0024reference",
            "name": "reference",
            "summary": "The\u0020unique\u0020payment\u0020\u0028order\u0029\u0020ID\u0020for\u0020future\u0020usage.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-ReferenceCommandAttributeTrait.html#property_reference"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\SaveCommandAttributeTrait",
            "name": "SaveCommandAttributeTrait",
            "summary": "Trait\u0020SaveCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-SaveCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\SaveCommandAttributeTrait\u003A\u003AsetSave\u0028\u0029",
            "name": "setSave",
            "summary": "Set\u0020the\u0020save\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-SaveCommandAttributeTrait.html#method_setSave"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\SaveCommandAttributeTrait\u003A\u003AgetSave\u0028\u0029",
            "name": "getSave",
            "summary": "Get\u0020the\u0020save\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-SaveCommandAttributeTrait.html#method_getSave"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\SaveCommandAttributeTrait\u003A\u003A\u0024save",
            "name": "save",
            "summary": "Indicates\u0020whether\u0020to\u0020save\u0020card\u0020data.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-SaveCommandAttributeTrait.html#property_save"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TemplateCommandAttributeTrait",
            "name": "TemplateCommandAttributeTrait",
            "summary": "Trait\u0020TemplateCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TemplateCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TemplateCommandAttributeTrait\u003A\u003AsetTemplate\u0028\u0029",
            "name": "setTemplate",
            "summary": "Set\u0020the\u0020template\u0020name.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TemplateCommandAttributeTrait.html#method_setTemplate"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TemplateCommandAttributeTrait\u003A\u003AgetTemplate\u0028\u0029",
            "name": "getTemplate",
            "summary": "Get\u0020the\u0020template\u0020name.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TemplateCommandAttributeTrait.html#method_getTemplate"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TemplateCommandAttributeTrait\u003A\u003A\u0024template",
            "name": "template",
            "summary": "The\u0020name\u0020of\u0020the\u0020template\u0020for\u0020the\u0020card\u0020input\u0020page.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TemplateCommandAttributeTrait.html#property_template"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TokenCommandAttributeTrait",
            "name": "TokenCommandAttributeTrait",
            "summary": "Trait\u0020TokenCommandAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TokenCommandAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TokenCommandAttributeTrait\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "Set\u0020the\u0020token\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TokenCommandAttributeTrait.html#method_setToken"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TokenCommandAttributeTrait\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Get\u0020the\u0020token\u0020attribute.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TokenCommandAttributeTrait.html#method_getToken"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes\\TokenCommandAttributeTrait\u003A\u003A\u0024token",
            "name": "token",
            "summary": "The\u0020card\u0027s\u0020unique\u0020token.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-Commands-Attributes-TokenCommandAttributeTrait.html#property_token"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\AmountJsonResponseAttributeTrait",
            "name": "AmountJsonResponseAttributeTrait",
            "summary": "Trait\u0020AmountJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-AmountJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\AmountJsonResponseAttributeTrait\u003A\u003AgetAmount\u0028\u0029",
            "name": "getAmount",
            "summary": "Get\u0020the\u0020amount\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-AmountJsonResponseAttributeTrait.html#method_getAmount"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ApprovalJsonResponseAttributeTrait",
            "name": "ApprovalJsonResponseAttributeTrait",
            "summary": "Trait\u0020ApprovalJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ApprovalJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ApprovalJsonResponseAttributeTrait\u003A\u003AgetApproval\u0028\u0029",
            "name": "getApproval",
            "summary": "Get\u0020the\u0020approval\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ApprovalJsonResponseAttributeTrait.html#method_getApproval"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\BillerJsonResponseAttributeTrait",
            "name": "BillerJsonResponseAttributeTrait",
            "summary": "Trait\u0020BillerJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-BillerJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\BillerJsonResponseAttributeTrait\u003A\u003AgetBiller\u0028\u0029",
            "name": "getBiller",
            "summary": "Get\u0020the\u0020biller\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-BillerJsonResponseAttributeTrait.html#method_getBiller"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\CodeJsonResponseAttributeTrait",
            "name": "CodeJsonResponseAttributeTrait",
            "summary": "Trait\u0020CodeJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-CodeJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\CodeJsonResponseAttributeTrait\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "Get\u0020the\u0020code\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-CodeJsonResponseAttributeTrait.html#method_getCode"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\CurrencyJsonResponseAttributeTrait",
            "name": "CurrencyJsonResponseAttributeTrait",
            "summary": "Trait\u0020CurrencyJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-CurrencyJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\CurrencyJsonResponseAttributeTrait\u003A\u003AgetCurrency\u0028\u0029",
            "name": "getCurrency",
            "summary": "Get\u0020the\u0020currency\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-CurrencyJsonResponseAttributeTrait.html#method_getCurrency"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\DatetimeJsonResponseAttributeTrait",
            "name": "DatetimeJsonResponseAttributeTrait",
            "summary": "Trait\u0020DatetimeJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-DatetimeJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\DatetimeJsonResponseAttributeTrait\u003A\u003AgetDatetime\u0028\u0029",
            "name": "getDatetime",
            "summary": "Get\u0020the\u0020datetime\u0020value\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-DatetimeJsonResponseAttributeTrait.html#method_getDatetime"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ExpiryJsonResponseAttributeTrait",
            "name": "ExpiryJsonResponseAttributeTrait",
            "summary": "Trait\u0020ExpiryJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ExpiryJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ExpiryJsonResponseAttributeTrait\u003A\u003AgetExpiry\u0028\u0029",
            "name": "getExpiry",
            "summary": "Get\u0020the\u0020expiry\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ExpiryJsonResponseAttributeTrait.html#method_getExpiry"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ExtraJsonResponseAttributeTrait",
            "name": "ExtraJsonResponseAttributeTrait",
            "summary": "Trait\u0020ExtraJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ExtraJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ExtraJsonResponseAttributeTrait\u003A\u003AgetExtra\u0028\u0029",
            "name": "getExtra",
            "summary": "Get\u0020the\u0020value\u0020of\u0020the\u0020\u0022extra\u0022\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ExtraJsonResponseAttributeTrait.html#method_getExtra"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\IssuerJsonResponseAttributeTrait",
            "name": "IssuerJsonResponseAttributeTrait",
            "summary": "Trait\u0020IssuerJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-IssuerJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\IssuerJsonResponseAttributeTrait\u003A\u003AgetIssuer\u0028\u0029",
            "name": "getIssuer",
            "summary": "Get\u0020the\u0020issuer\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-IssuerJsonResponseAttributeTrait.html#method_getIssuer"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\MessageJsonResponseAttributeTrait",
            "name": "MessageJsonResponseAttributeTrait",
            "summary": "Trait\u0020MessageJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-MessageJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\MessageJsonResponseAttributeTrait\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "Get\u0020the\u0020message\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-MessageJsonResponseAttributeTrait.html#method_getMessage"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\PanJsonResponseAttributeTrait",
            "name": "PanJsonResponseAttributeTrait",
            "summary": "Trait\u0020PanJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-PanJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\PanJsonResponseAttributeTrait\u003A\u003AgetPan\u0028\u0029",
            "name": "getPan",
            "summary": "Get\u0020the\u0020PAN\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-PanJsonResponseAttributeTrait.html#method_getPan"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ReferenceJsonResponseAttributeTrait",
            "name": "ReferenceJsonResponseAttributeTrait",
            "summary": "Trait\u0020ReferenceJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ReferenceJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ReferenceJsonResponseAttributeTrait\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "Get\u0020the\u0020reference\u0020value\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ReferenceJsonResponseAttributeTrait.html#method_getReference"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\RrnJsonResponseAttributeTrait",
            "name": "RrnJsonResponseAttributeTrait",
            "summary": "Trait\u0020RrnJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-RrnJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\RrnJsonResponseAttributeTrait\u003A\u003AgetRrn\u0028\u0029",
            "name": "getRrn",
            "summary": "Get\u0020the\u0020RRN\u0020\u0028Retrieval\u0020Reference\u0020Number\u0029\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-RrnJsonResponseAttributeTrait.html#method_getRrn"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\StatusJsonResponseAttributeTrait",
            "name": "StatusJsonResponseAttributeTrait",
            "summary": "Trait\u0020StatusJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-StatusJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\StatusJsonResponseAttributeTrait\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "Get\u0020the\u0020status\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-StatusJsonResponseAttributeTrait.html#method_getStatus"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\SystemJsonResponseAttributeTrait",
            "name": "SystemJsonResponseAttributeTrait",
            "summary": "Trait\u0020SystemJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-SystemJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\SystemJsonResponseAttributeTrait\u003A\u003AgetSystem\u0028\u0029",
            "name": "getSystem",
            "summary": "Get\u0020the\u0020system\u0020attribute\u0020from\u0020the\u0020JSON\u0020response\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-SystemJsonResponseAttributeTrait.html#method_getSystem"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ThreeDSJsonResponseAttributeTrait",
            "name": "ThreeDSJsonResponseAttributeTrait",
            "summary": "Trait\u0020ThreeDSJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ThreeDSJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\ThreeDSJsonResponseAttributeTrait\u003A\u003Aget3ds\u0028\u0029",
            "name": "get3ds",
            "summary": "Get\u0020the\u0020\u00223ds\u0022\u0020attribute\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-ThreeDSJsonResponseAttributeTrait.html#method_get3ds"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\TokenJsonResponseAttributeTrait",
            "name": "TokenJsonResponseAttributeTrait",
            "summary": "Trait\u0020TokenJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-TokenJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\TokenJsonResponseAttributeTrait\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Get\u0020the\u0020value\u0020of\u0020the\u0020\u0022token\u0022\u0020attribute\u0020from\u0020the\u0020response\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-TokenJsonResponseAttributeTrait.html#method_getToken"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\TypeJsonResponseAttributeTrait",
            "name": "TypeJsonResponseAttributeTrait",
            "summary": "Trait\u0020TypeJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-TypeJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\TypeJsonResponseAttributeTrait\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020value\u0020of\u0020the\u0020\u0022type\u0022\u0020attribute\u0020from\u0020the\u0020response\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-TypeJsonResponseAttributeTrait.html#method_getType"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\UrlJsonResponseAttributeTrait",
            "name": "UrlJsonResponseAttributeTrait",
            "summary": "Trait\u0020UrlJsonResponseAttributeTrait",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-UrlJsonResponseAttributeTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes\\UrlJsonResponseAttributeTrait\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "Get\u0020the\u0020URL\u0020from\u0020the\u0020JSON\u0020response.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-Attributes-UrlJsonResponseAttributeTrait.html#method_getUrl"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\ResponseDataTrait",
            "name": "ResponseDataTrait",
            "summary": "The\u0020ResponseDataTrait\u0020provides\u0020a\u0020trait\u0020for\u0020handling\u0020JSON\u0020response\u0020data.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-ResponseDataTrait.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\ResponseDataTrait\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020JSON\u0020response\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-ResponseDataTrait.html#method_handle"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\ResponseDataTrait\u003A\u003A\u0024response",
            "name": "response",
            "summary": "The\u0020response\u0020object.",
            "url": "classes/EasyPay-PHP-Yigim-Traits-JsonResponse-ResponseDataTrait.html#property_response"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Abstracts",
            "name": "Abstracts",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-abstracts.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim",
            "name": "Yigim",
            "summary": "",
            "url": "namespaces/easypay-php-yigim.html"
        },                {
            "fqsen": "\\EasyPay\\PHP",
            "name": "PHP",
            "summary": "",
            "url": "namespaces/easypay-php.html"
        },                {
            "fqsen": "\\EasyPay",
            "name": "EasyPay",
            "summary": "",
            "url": "namespaces/easypay.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Attributers",
            "name": "Attributers",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands-attributers.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\EndpointProviders",
            "name": "EndpointProviders",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands-endpointproviders.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands-factories.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseData",
            "name": "ResponseData",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands-responsedata.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Commands\\ResponseHandlers",
            "name": "ResponseHandlers",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-commands-responsehandlers.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-contracts.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-enums.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-exceptions.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Executors",
            "name": "Executors",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-executors.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-facades.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-helpers.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-traits-commands-attributes.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-traits-commands.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-traits.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-traits-jsonresponse-attributes.html"
        },                {
            "fqsen": "\\EasyPay\\PHP\\Yigim\\Traits\\JsonResponse",
            "name": "JsonResponse",
            "summary": "",
            "url": "namespaces/easypay-php-yigim-traits-jsonresponse.html"
        }            ]
);
